### ISSUE TITLE
Add Utterances comments

### ISSUE THREAD

**Issue by techboyg5** [raux/raux.github.io#2]
Add Utterances comments please. Thank you!

**Comment by techboyg5** [comment]
Why did you close this issue without explaining it?

**Comment by raux** [comment]
I do not understand what it means the utterances comments means. Please can you explain more?

**Comment by techboyg5** [comment]
> 
> 
> I do not understand what it means the utterances comments means. Please can you explain more?

[Utterances](https://utteranc.es/) is a comments system for GitHub Pages and other static websites. It uses GitHub Issues for comments.

**Comment by raux** [comment]
Ok. I will reopen, but will first look at the system before deciding whether or not to add this.

Thank you for making this system aware to me.

**Comment by techboyg5** [comment]
> 
> 
> Ok. I will reopen, but will first look at the system before deciding whether or not to add this.
> 
> Thank you for making this system aware to me.

You're welcome! By the way, it's very easy to setup:
1. Create a public repo called `raux/comments`. Make sure that it has issues enabled.
2. [Authorize utterances inside the `raux/comments` repo.](https://github.com/apps/utterances)
3. Add the comments section to your pages:
`<div id="comments">`
`<h2>Comments</h2>`
`<script src="https://utteranc.es/client.js"`
`repo="raux/comments"`
`issue-term="title"`
`theme="github-light"`
`crossorigin="anonymous"`
`async>`
`</script>`
`</div>`

**Comment by techboyg5** [comment]
Now let's focus on the issue again. It looks like your account got suspended somehow, but it looks like it's back again.

**Comment by raux** [comment]
Sorry, I am still trying to figure out how the comments could be useful for my website. I will get back to you soon when I decide how to implement the technology.

**Comment by techboyg5** [comment]
> Sorry, I am still trying to figure out how the comments could be useful for my website. I will get back to you soon when I decide how to implement the technology.

Okay, thank you! If you decide yes then follow the instructions above.

**Comment by techboyg5** [comment]
Let's push this issue back up again! And think again because this issue hasn't had any activity for the last 2 weeks.

**Comment by raux** [comment]
new hugo template
